document.addEventListener('DOMContentLoaded', () =>{

    // lista de todos los ingredientes disponibles
    const ingredientes = [
        { imagenSrc: 'assets/img/aguacate.webp', name: 'Aguacate' },
        { imagenSrc: 'assets/img/brocoli.webp', name: 'Brocoli' },
        { imagenSrc: 'assets/img/carne.webp', name: 'Carne' },
        { imagenSrc: 'assets/img/cebolla.webp', name: 'Cebolla' },
        { imagenSrc: 'assets/img/coliflor.webp', name: 'Coliflor' },
        { imagenSrc: 'assets/img/patatas.webp', name: 'Patatas' },
        { imagenSrc: 'assets/img/pescado.webp', name: 'Pescado' },
        { imagenSrc: 'assets/img/pimientos.webp', name: 'Pimientos' },
        { imagenSrc: 'assets/img/queso.webp', name: 'Queso' },
        { imagenSrc: 'assets/img/tomate.webp', name: 'Tomate' },
        { imagenSrc: 'assets/img/huevos.webp', name: 'Huevos' },
        { imagenSrc: 'assets/img/arroz.webp', name: 'Arroz' },
        { imagenSrc: 'assets/img/champinones.webp', name: 'Champiñones' },
        { imagenSrc: 'assets/img/pasta.webp', name: 'Pasta' },
        { imagenSrc: 'assets/img/alubias.webp', name: 'Alubias' },
        { imagenSrc: 'assets/img/harina.webp', name: 'Harina' },
        { imagenSrc: 'assets/img/ajo.webp', name: 'Ajo' },
        { imagenSrc: 'assets/img/calabacin.webp', name: 'Calabacin' },
        { imagenSrc: 'assets/img/zanahoria.webp', name: 'Zanahoria' },
        { imagenSrc: 'assets/img/guisantes.webp', name: 'Guisantes' },
        { imagenSrc: 'assets/img/atun.webp', name: 'Atún' },
        { imagenSrc: 'assets/img/pollo.webp', name: 'Pollo' },
        { imagenSrc: 'assets/img/berenjena.webp', name: 'Berenjena' },
        { imagenSrc: 'assets/img/batatas.webp', name: 'Batatas' },
        { imagenSrc: 'assets/img/pan.webp', name: 'Pan' },
        { imagenSrc: 'assets/img/banana.webp', name: 'Banana' },
        { imagenSrc: 'assets/img/fresa.webp', name: 'Fresa' },
        { imagenSrc: 'assets/img/mantequilla.webp', name: 'Mantequilla' },
        { imagenSrc: 'assets/img/manzana.webp', name: 'Manzana' },
        { imagenSrc: 'assets/img/leche.webp', name: 'Leche' },
        { imagenSrc: 'assets/img/sandia.webp', name: 'Sandia' },
        { imagenSrc: 'assets/img/mango.webp', name: 'Mango' },
        { imagenSrc: 'assets/img/naranja.webp', name: 'Naranja' },
        { imagenSrc: 'assets/img/pina.webp', name: 'Piña' },
        { imagenSrc: 'assets/img/pera.webp', name: 'Pera' },
        { imagenSrc: 'assets/img/limon.webp', name: 'Limón' },
    ];
});